!!python/object:argparse.Namespace
anneal_lr: true
batch_size: 1024
buffer_batches: 1
buffer_size: 1024
clip_coef: 0.2
clip_vloss: true
cuda: true
device: !!python/object/apply:torch.device
- cpu
ent_coef: 0.01
env_id: CartPole-v1
eval_episodes: 20
eval_freq: 10
exp_name: ppo_props_discrete
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.001
log_stats: 1
max_grad_norm: 0.5
minibatch_size: 32
norm_adv: true
normalization_dir: null
num_envs: 1
num_minibatches: 32
num_steps: 1024
policy_path: null
props: 0
props_adv: false
props_anneal_lr: 0
props_clip_coef: 0.3
props_eval: false
props_lambda: 0.3
props_learning_rate: 1.0e-05
props_max_grad_norm: 0.5
props_minibatch_size: 224
props_num_minibatches: 4
props_num_steps: 128
props_target_kl: 0.03
props_update_epochs: 4
results_dir: discrete_experts
results_subdir: ''
ros: 0
run_id: null
save_dir: discrete_experts/CartPole-v1/ppo_buffer//run_1
se: 0
se_epochs: 250
se_freq: 10
se_lr: 0.001
se_ref: 1
seed: 1271979217
target_kl: 0.03
torch_deterministic: true
total_timesteps: 500000.0
track: false
update_epochs: 10
vf_coef: 0.5
wandb_entity: null
wandb_login_key: null
wandb_project_name: cleanRL
