"""

"""



PPOROS_PARAMS = {
    'Swimmer-v4': {
        2: {
            'path': 'condor_new/ppo_ros_b2_swimmer_final/results/Swimmer-v4/ppo_ros/history_2/num_steps_4096/num_steps_256/lr_0.001/lr_1e-05/kl_0.05/kl_0.05/epochs_10/epochs_8/clip_0.3/',
            'num_steps': 2048,
            'lr': 1e-3,
            'update_epochs': 10,
            'target_kl': 0.05,
            'ros_num_steps': 256,
            'ros_lr': 1e-5,
            'ros_update_epochs': 8,
            'ros_target_kl': 0.05,
            'ros_clip_coef': 0.3,
        },
        4: { # done 50
            'num_steps': 1024,
            'lr': 1e-3,
            'ros_lr': 1e-4,
            'ros_update_epochs': 4,
            'ros_clip_coef': 0.3,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'HalfCheetah-v4': {
        2: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
        4: {
            'num_steps': 1024,
            'lr': 1e-4,
            'ros_lr': 1e-3,
            'ros_update_epochs': 4,
            'ros_clip_coef': 0.1,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'Hopper-v4': {
        # 2: { # condor_X/2048_hopper
        #     'path': './condor_fix/fix_hopper_b2/results/Hopper-v4/ppo_ros/b_2/s_2048/s_2048/lr_0.0001/lr_0.0001/kl_0.03/kl_0.05/e_8/c_0.3/a_1',
        #     'num_steps': 2048,
        #     'lr': 1e-4,
        #     'target_kl': 0.03,
        #     'ros_num_steps': 2048,
        #     'ros_lr': 1e-3,
        #     'ros_update_epochs': 16,
        #     'ros_kl': 0.05,
        #     'ros_clip_coef': 0.3,
        # },
        2: {  # condor_X/2048_hopper
            'path': 'condor_fix/fix_kl/results/Hopper-v4/ppo_ros/b_2/l_0.5/s_2048/s_2048/lr_0.0001/lr_0.001/kl_0.03/kl_0.05/e_16/c_0.3/a_1/',
            'num_steps': 2048,
            'lr': 1e-4,
            'target_kl': 0.03,
            'ros_num_steps': 2048,
            'ros_lr': 1e-3,
            'ros_update_epochs': 16,
            'ros_lambda': 0.5,
            'ros_kl': 0.05, # 0.1
            'ros_clip_coef': 0.3,
        },
        4: { #
            'num_steps': 2048,
            'lr': 1e-4,
            'target_kl': 0.03,
            'ros_num_steps': 2048,
            'ros_lr': 1e-3,
            'ros_update_epochs': 8,
            'ros_kl': 0.05,
            'ros_clip_coef': 0.3,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'Walker2d-v4': {
        2: { # didn't check clip0.3
            'path': 'condor_new/ppo_ros_b2_swimmer_final/results/Swimmer-v4/ppo_ros/history_2/num_steps_4096/num_steps_256/lr_0.001/lr_1e-05/kl_0.05/kl_0.05/epochs_10/epochs_8/clip_0.3/',
            'num_steps': 2048,
            'lr': 1e-3,
            'update_epochs': 10,
            'target_kl': 0.03,
            'ros_num_steps': 256,
            'ros_lr': 1e-4,
            'ros_update_epochs': 16,
            'ros_lambda': 0.001,
            'ros_target_kl': 0.1,
            'ros_clip_coef': 0.3,
        },
        4: {
            'num_steps': 1024,
            'lr': 1e-4,
            'ros_lr': 5e-4,
            'ros_update_epochs': 2,
            'ros_clip_coef': 0.1,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'Ant-v4': {
        2: {
            'num_steps': 2048,
            'lr': 1e-4,
            'ros_lr': 1e-4,
            'ros_update_epochs': 32,
            'ros_kl': 0.05,
        },
        4: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'Humanoid-v4': {
        2: {
            'path': './condor_X/X_ros_humanoid_b2_sweep/results/Humanoid-v4/ppo_ros/b_2/s_8192/lr_0.0001/lr_0.0001/kl_0.03/kl_0.02/e_16/c_0.2/',
            'num_steps': 8192,
            'lr': 1e-4,
            'ros_lr': 1e-4,
            'ros_update_epochs': 4,
            'ros_kl': 0.05,
        },
        4: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
}


OLD_PPOROS_PARAMS = {
    'Swimmer-v4': {
        2: {
            'path': './ppo_ros_b2_swimmer_final/results/Swimmer-v4/ppo_ros/history_2/num_steps_4096/num_steps_256/lr_0.001/lr_1e-05/kl_0.05/kl_0.05/epochs_10/epochs_8/clip_0.3/',
            'num_steps': 2048,
            'lr': 1e-3,
            'update_epochs': 10,
            'target_kl': 0.05,
            'ros_num_steps': 256,
            'ros_lr': 1e-5,
            'ros_update_epochs': 8,
            'ros_target_kl': 0.05,
            'ros_clip_coef': 0.3,
        },
        4: { # done 50
            'num_steps': 1024,
            'lr': 1e-3,
            'ros_lr': 1e-4,
            'ros_update_epochs': 4,
            'ros_clip_coef': 0.3,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'HalfCheetah-v4': {
        2: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
        4: {
            'num_steps': 1024,
            'lr': 1e-4,
            'ros_lr': 1e-3,
            'ros_update_epochs': 4,
            'ros_clip_coef': 0.1,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'Hopper-v4': {
        2: { # VERIFIED
            'path': './fix_hopper_b2/results/Hopper-v4/ppo_ros/b_2/s_2048/s_2048/lr_0.0001/lr_0.0001/kl_0.03/kl_0.1/e_8/c_0.3/a_1',
            'num_steps': 1024,
            'lr': 1e-4,
            'update_epochs': 10,
            'target_kl': 0.03,
            'ros_num_steps': 256,
            'ros_lr': 1e-4, #or 1e-3
            'ros_update_epochs': 8,
            'ros_target_kl': 0.05,
            'ros_clip_coef': 0.3,
        },
        4: { # VERIFIED
            'path': 'condor_5/ros_b24_t0.03/results/Hopper-v4/ppo_ros/history_4/num_steps_2048/num_steps_256/lr_0.0001/lr_0.001/kl_0.03/kl_0.05/epochs_10/epochs_8/clip_0.3',
            'num_steps': 2048,
            'lr': 1e-4,
            'update_epochs': 10,
            'target_kl': 0.03,
            'ros_num_steps': 256,
            'ros_lr': 1e-3,
            'ros_update_epochs': 8,
            'ros_target_kl': 0.05,
            'ros_clip_coef': 0.3,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'Walker2d-v4': {
        2: { # didn't check clip0.3
            'num_steps': 1024,
            'lr': 1e-4,
            'ros_lr': 1e-4,
            'ros_update_epochs': 8,
            'ros_clip_coef': 0.1,
            'ros_kl': 0.05,
        },
        4: {
            'num_steps': 1024,
            'lr': 1e-4,
            'ros_lr': 5e-4,
            'ros_update_epochs': 2,
            'ros_clip_coef': 0.1,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'Ant-v4': {
        2: {
            'num_steps': 2048,
            'lr': 1e-4,
            'ros_lr': 1e-4,
            'ros_update_epochs': 32,
            'ros_kl': 0.05,
        },
        4: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
    'Humanoid-v4': {
        2: {
            'num_steps': 8192,
            'lr': 1e-4,
            'ros_lr': 1e-4,
            'ros_update_epochs': 4,
            'ros_kl': 0.05,
        },
        4: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
        8: {
            'num_steps': 0,
            'lr': 0,
            'ros_lr': 0,
            'ros_update_epochs': 0,
            'ros_kl': 0.05,
        },
    },
}