!!python/object:argparse.Namespace
anneal_lr: true
batch_size: 8192
beta: false
capture_video: false
clip_coef: 0.2
clip_vloss: true
compute_sampling_error: 0
cuda: true
ent_coef: 0.01
env_id: Humanoid-v4
eval_episodes: 20
eval_freq: 10
exp_name: ppo_continuous
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0001
max_grad_norm: 0.5
minibatch_size: 256
norm_adv: true
normalization_dir: null
num_envs: 1
num_minibatches: 32
num_steps: 8192
policy_path: null
results_dir: results
results_subdir: num_steps_8192/lr_0.0001/kl_None
run_id: null
save_dir: results/Humanoid-v4/ppo/num_steps_8192/lr_0.0001/kl_None/run_1
save_policy: true
seed: 0
target_kl: null
torch_deterministic: true
total_timesteps: 6000000
track: false
update_epochs: 10
vf_coef: 0.5
wandb_entity: null
wandb_project_name: PPOROS
