!!python/object:argparse.Namespace
anneal_lr: true
batch_size: 2048
buffer_history: 4
capture_video: false
clip_coef: 0.2
clip_vloss: true
compute_sampling_error: false
cuda: true
ent_coef: 0.01
ent_coef_ros: 0.01
env_id: Hopper-v4
eval_episodes: 20
eval_freq: 10
exp_name: ppo_continuous
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0001
learning_rate_ros: 0.0001
max_grad_norm: 0.5
minibatch_size: 64
norm_adv: true
num_envs: 1
num_minibatches: 32
num_steps: 2048
policy_path: null
results_dir: results
results_subdir: ''
ros: true
run_id: null
save_dir: results/Hopper-v4/ppo//run_10
seed: 0
target_kl: null
torch_deterministic: true
total_timesteps: 1000000
track: false
update_epochs: 10
vf_coef: 0.5
wandb_entity: null
wandb_project_name: cleanRL
